name: .NET CI ParseAndRecreation
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x 

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test (no build)
      run: dotnet test -c Release --no-build

    - name: dotnet-coverage (collect Cobertura)
      run: |
          dotnet tool install -g dotnet-coverage
          mkdir -p artifacts/coverage
          ~/.dotnet/tools/dotnet-coverage collect 'dotnet test -c Release --no-build' \
          -f cobertura -o artifacts/coverage/coverage.cobertura.xml

    - name: ReportGenerator (HTML + text summary)
      run: |
          dotnet tool install -g dotnet-reportgenerator-globaltool
          ~/.dotnet/tools/reportgenerator \
          -reports:'artifacts/coverage/coverage.cobertura.xml' \
          -targetdir:'artifacts/coverage-report' \
          -reporttypes:'HtmlInline;TextSummary'
          
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: metrics-artifacts
        path: |
          artifacts/coverage-report
