name: Metrics
on: [push, pull_request]

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore

      - name: Test (no build)
        run: dotnet test -c Release --no-build

      - name: dotnet-coverage (collect Cobertura)
        run: |
            dotnet tool install -g dotnet-coverage
            mkdir -p artifacts/coverage
            ~/.dotnet/tools/dotnet-coverage collect 'dotnet test -c Release --no-build' \
            -f cobertura -o artifacts/coverage/coverage.cobertura.xml

      - name: ReportGenerator (HTML + text summary)
        run: |
            dotnet tool install -g dotnet-reportgenerator-globaltool
            ~/.dotnet/tools/reportgenerator \
            -reports:'artifacts/coverage/coverage.cobertura.xml' \
            -targetdir:'artifacts/coverage-report' \
            -reporttypes:'HtmlInline;TextSummary'
      - name: Install scc
        run: |
          set -eux
          SCC_VERSION=3.5.0
          curl -L "https://github.com/boyter/scc/releases/download/v${SCC_VERSION}/scc_${SCC_VERSION}_linux_amd64.tar.gz" -o scc.tgz
          tar -xzf scc.tgz scc
          sudo mv scc /usr/local/bin/scc
          scc --version

      - name: Run scc
        run: |
          mkdir -p artifacts/metrics
          scc --exclude-dir obj,bin --include-ext cs . | tee artifacts/metrics/scc.txt

      - name: Upload metrics artifact
        uses: actions/upload-artifact@v4
        with:
          name: scc-metrics
          path: artifacts/metrics/scc.txt

      - name: Job summary
        run: |
          echo "## Code metrics" >> $GITHUB_STEP_SUMMARY
          echo "### Coverage" >> $GITHUB_STEP_SUMMARY
          if [ -f artifacts/coverage-report/Summary.txt ]; then
            echo '```' >> $GITHUB_STEP_SUMMARY
            cat artifacts/coverage-report/Summary.txt >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
          else
            echo "_No coverage files found._" >> $GITHUB_STEP_SUMMARY
          fi
          echo "### SLOC/Complexity (scc)" >> $GITHUB_STEP_SUMMARY
          echo "| Metric | Value |" >> $GITHUB_STEP_SUMMARY
          echo "|--|--:|" >> $GITHUB_STEP_SUMMARY
          jq -r '.[] | select(.Name=="C#") |
            "| Files | \(.Count) |\n| Code | \(.Code) |\n| Comments | \(.Comment) |\n| Blanks | \(.Blank) |\n| Complexity | \(.Complexity) |"
            ' artifacts/scc.json >> $GITHUB_STEP_SUMMARY

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: metrics-artifacts
          path: |
            artifacts/coverage-report
            artifacts/scc.json
            artifacts/scc-by-file.txt
