name: Metrics
on: [push, pull_request]

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore

      - name: Test + Coverage (Coverlet)
        run: >
          dotnet test -c Release --no-build
          /p:CollectCoverage=true
          /p:CoverletOutputFormat=cobertura
          /p:CoverletOutput=artifacts/coverage/

      - name: ReportGenerator (HTML + text summary)
        run: |
          dotnet tool install -g dotnet-reportgenerator-globaltool
          ~/.dotnet/tools/reportgenerator \
            -reports:'**/artifacts/coverage/coverage.cobertura.xml' \
            -targetdir:'artifacts/coverage-report' \
            -reporttypes:'HtmlInline;TextSummary'

      - name: scc (SLOC & complexity)
        run: |
          mkdir -p artifacts
          docker run --rm -v "${{ github.workspace }}:/src" boyter/scc:latest \
            --include-ext cs --exclude-dir obj,bin --format json /src > artifacts/scc.json
          docker run --rm -v "${{ github.workspace }}:/src" boyter/scc:latest \
            --include-ext cs --exclude-dir obj,bin --by-file /src > artifacts/scc-by-file.txt

      - name: Job summary
        run: |
          echo "## Code metrics" >> $GITHUB_STEP_SUMMARY
          echo "### Coverage" >> $GITHUB_STEP_SUMMARY
          if [ -f artifacts/coverage-report/Summary.txt ]; then
            echo '```' >> $GITHUB_STEP_SUMMARY
            cat artifacts/coverage-report/Summary.txt >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
          else
            echo "_No coverage files found._" >> $GITHUB_STEP_SUMMARY
          fi
          echo "### SLOC/Complexity (scc)" >> $GITHUB_STEP_SUMMARY
          echo "| Metric | Value |" >> $GITHUB_STEP_SUMMARY
          echo "|--|--:|" >> $GITHUB_STEP_SUMMARY
          jq -r '.[] | select(.Name=="C#") |
            "| Files | \(.Count) |\n| Code | \(.Code) |\n| Comments | \(.Comment) |\n| Blanks | \(.Blank) |\n| Complexity | \(.Complexity) |"
            ' artifacts/scc.json >> $GITHUB_STEP_SUMMARY

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: metrics-artifacts
          path: |
            artifacts/coverage-report
            artifacts/scc.json
            artifacts/scc-by-file.txt
